### ISSUE TITLE
Error generating diagram from Oracle Schema in pdf format

### ISSUE THREAD

**Issue by javc1974** [sualeh/SchemaCrawler#32] opened 2016-02-12 11:54 UTC
Congratulations for your job!!!

Feb 12, 2016 10:46:41 AM sf.util.DatabaseUtility executeSql
WARNING: Error executing SQL, SELECT /*+ PARALLEL(AUTO) */
  NULL AS TABLE_CATALOG,
  TABLES.OWNER AS TABLE_SCHEMA,
  TABLES.TABLE_NAME,
  DBMS_METADATA.GET_DDL('TABLE', TABLES.TABLE_NAME, TABLES.OWNER) 
    AS TABLE_DEFINITION
FROM
  ALL_TABLES TABLES
  INNER JOIN ALL_USERS USERS
    ON TABLES.OWNER = USERS.USERNAME
WHERE
  USERS.USERNAME NOT IN 
    ('ANONYMOUS', 'APEX_PUBLIC_USER', 'BI', 'CTXSYS', 'DBSNMP', 'DIP', 
    'EXFSYS', 'FLOWS_30000', 'FLOWS_FILES', 'HR', 'IX', 'LBACSYS', 
    'MDDATA', 'MDSYS', 'MGMT_VIEW', 'OE', 'OLAPSYS', 'ORACLE_OCM', 
    'ORDPLUGINS', 'ORDSYS', 'OUTLN', 'OWBSYS', 'PM', 'SCOTT', 'SH', 
    'SI_INFORMTN_SCHEMA', 'SPATIAL_CSW_ADMIN_USR', 'SPATIAL_WFS_ADMIN_USR', 
    'SYS', 'SYSMAN', 'SYSTEM', 'TSMSYS', 'WKPROXY', 'WKSYS', 'WK_TEST', 
    'WMSYS', 'XDB', 'XS$NULL')  
  AND NOT REGEXP_LIKE(USERS.USERNAME, '^APEX_[0-9]{6}$')
  AND NOT REGEXP_LIKE(USERS.USERNAME, '^FLOWS_[0-9]{5}$')
  AND TABLES.TABLE_NAME NOT LIKE 'BIN$%'
ORDER BY
  TABLE_SCHEMA,
  TABLE_NAME;

java.sql.SQLException: ORA-31603: object "TOAD_PLAN_TABLE" of type TABLE not found in schema "CUA_DATA_PRO"
ORA-06512: at "SYS.DBMS_METADATA", line 5088
ORA-06512: at "SYS.DBMS_METADATA", line 7589
ORA-06512: at line 1

This error is because TOAD_PLAN_TABLE is a global temporary table of user/schema CUA_DATA_PRO.

It would be useful a flag for excluding Oracle temporary tables that when you use it in this query add the clause "AND TEMPORARY!='Y'"

Thank you very much

**Comment by sualeh** [comment] 2016-02-13 03:54
I cannot reproduce the problem. What version of Oracle are you using? What version of the Oracle JDBC driver are you using?

**Comment by javc1974** [comment] 2016-02-16 00:37
I am using Oracle RDBMS 11.2.0.3 and Oracle JDBC Driver 11.2.0.4
Thanks

Date: Fri, 12 Feb 2016 19:54:32 -0800

**Comment by adriens** [comment] 2016-02-16 01:01
Can you provide the command line ?

**Comment by sualeh** [comment] 2016-02-16 02:25
Also, please try using the latest version of the Oracle JDBC driver, 12.1.0.2. There are bugs in the earlier versions of the driver.

**Comment by adriens** [comment] 2016-02-19 00:33
Any news @javc1974 ? Did you make it work ?

**Comment by sualeh** [comment] 2016-02-22 13:59
@javc1974 - I will close this issue if I do not hear back from you.

**Comment by sualeh** [comment] 2016-02-25 01:54
No response.

**Closed by sualeh** 2016-02-25 01:54 UTC
